# Configuration file for myApp

# The port to listen on
port: 8127

# The maximum number of queued incoming connections
backlog: 100

# IP address
ip: "51.222.166.68"

# Length of the password
passLength: 10

# Type of protocol e.g. "http" or "https"
protocol: "http"

# Whether or not the file should be cleared on restart
clearFiles: true

# A set password that should be used. Set to a value of '0' to generate random on startup
setPassword: "0"

# Whether or not to send a set-password URL on start-up.
# e.g. "Password for NotABackdoor: http://ip:port/api/set-password/password"
sendPasswordLink: true

# List of file extensions that can be opened
allowedFileExtensions:
  - "txt"
  - "yml"
  - "yaml"
  - "json"
  - "xml"
  - "md"
  - "log"
  - "csv"
  - "ini"
  - "cfg"
  - "html"
  - "htm"
  - "css"
  - "js"
  - "sql"
  - "java"
  - "py"
  - "rb"
  - "php"
  - "c"
  - "cpp"
  - "h"
  - "hpp"
  - "cs"
  - "properties"
  - "ts"
  - "sh"
  - "bat"
  - "ps1"
  - "r"
  - "perl"
  - "pl"
  - "lua"
  - "swift"
  - "go"
  - "scala"
  - "kotlin"
  - "rust"
  - "groovy"
  - "coffee"
  - "scss"
  - "sass"
  - "env"
  - "sk"
  - "config"

